### ISSUE TITLE
Accidental Code Duplication

### ISSUE THREAD

**Issue by dechristopher** [sacert/SoundSea#11]
In SoundSea/src/settings/UserPreferences.java you've duplicated the last two lines of the setDirectory method as shown here:

public static void setDirectory(String dir) {
        userPrefs.put("folderDirectory", dir + File.separatorChar);
        FXController.folderDirectory = userPrefs.get("folderDirectory", null);
}
        **FXController.folderDirectory = userPrefs.get("folderDirectory", null);
}**

**Comment by sacert** [comment]
Good catch, fixed it up and committed.
